import { xchacha20poly1305 } from '@noble/ciphers/chacha.js';
import { pbkdf2 } from '@noble/hashes/pbkdf2.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { utf8ToBytes } from '@noble/hashes/utils.js';

import { BackupError } from './errors';
import { frameAssociatedData, frameNonce, NONCE_BYTES, SALT_BYTES } from './format';

/**
 * Key derivation and frame sealing for the `.evault` container.
 *
 * XChaCha20-Poly1305 over PBKDF2-HMAC-SHA256. ChaCha rather than AES because
 * this runs in JavaScript on Hermes, where there is no AES-NI to reach and
 * ChaCha is the faster of the two by a wide margin — and a backup that includes
 * attachments is tens of megabytes of symmetric work. The extended 24-byte
 * nonce is what makes a per-frame nonce derivable from one random base without
 * a birthday-bound argument.
 *
 * PBKDF2 rather than Argon2id because the app already depends on it (F9's PIN)
 * and Argon2 would mean a third dependency with a WASM path unproven on Hermes.
 * That is a deliberate trade: PBKDF2 is not memory-hard, so a weak passphrase
 * gets less protection here than it would under Argon2id. The passphrase policy
 * in `password.ts` is what carries that weight instead.
 *
 * Everything in this module is pure: the salt and nonce are generated by the
 * caller and passed in, so a test can reproduce a byte-identical container.
 */

export const DERIVED_KEY_BYTES = 32;

/**
 * Half of OWASP's 600,000 for PBKDF2-HMAC-SHA256, and deliberately so: this is
 * JavaScript on Hermes, where the full figure costs many seconds on an export
 * the user is watching. The count is written into the header, so raising it
 * later applies to new backups without making old ones unreadable.
 *
 * Unmeasured on a real device. If it proves slow, lower it here — nothing else
 * has to change.
 */
export const PBKDF2_ITERATIONS = 300_000;

export interface KdfParameters {
  salt: Uint8Array;
  iterations: number;
}

/**
 * Stretches a passphrase into the container key.
 *
 * The passphrase is converted to bytes and never retained: no module-level
 * cache, no logging, and the caller holds the derived key only for as long as
 * one export or import runs. JavaScript cannot promise the bytes are wiped from
 * memory afterwards, and pretending otherwise would be worse than saying so.
 */
export function deriveKey(password: string, { salt, iterations }: KdfParameters): Uint8Array {
  if (salt.length !== SALT_BYTES) {
    throw new BackupError('corrupt', `Salt must be ${SALT_BYTES} bytes, got ${salt.length}.`);
  }

  if (!Number.isInteger(iterations) || iterations < 1) {
    throw new BackupError('corrupt', 'Iteration count must be a positive integer.');
  }

  return pbkdf2(sha256, utf8ToBytes(password), salt, { c: iterations, dkLen: DERIVED_KEY_BYTES });
}

function cipherFor(key: Uint8Array, baseNonce: Uint8Array, frameIndex: number, version: number) {
  if (key.length !== DERIVED_KEY_BYTES) {
    throw new BackupError('corrupt', `Key must be ${DERIVED_KEY_BYTES} bytes, got ${key.length}.`);
  }

  if (baseNonce.length !== NONCE_BYTES) {
    throw new BackupError('corrupt', `Nonce must be ${NONCE_BYTES} bytes.`);
  }

  return xchacha20poly1305(
    key,
    frameNonce(baseNonce, frameIndex),
    frameAssociatedData(version, frameIndex),
  );
}

export function sealFrame(
  key: Uint8Array,
  baseNonce: Uint8Array,
  frameIndex: number,
  version: number,
  plaintext: Uint8Array,
): Uint8Array {
  return cipherFor(key, baseNonce, frameIndex, version).encrypt(plaintext);
}

/**
 * Opens one frame, or throws.
 *
 * `reason` is the caller's: a failure on frame 0 is overwhelmingly a wrong
 * password, while a failure on a later frame — after the password has already
 * proved itself — means the file is damaged. Only the caller knows which frame
 * this is, so only the caller can say.
 */
export function openFrame(
  key: Uint8Array,
  baseNonce: Uint8Array,
  frameIndex: number,
  version: number,
  frame: Uint8Array,
  reason: 'wrong-password' | 'corrupt',
): Uint8Array {
  try {
    return cipherFor(key, baseNonce, frameIndex, version).decrypt(frame);
  } catch (cause) {
    if (cause instanceof BackupError) {
      throw cause;
    }

    throw new BackupError(
      reason,
      reason === 'wrong-password'
        ? 'The backup could not be opened with that password.'
        : `Frame ${frameIndex} failed authentication; the backup file is damaged.`,
      cause,
    );
  }
}
