/**
 * Extracted verbatim from design/stitch_expiryvault_mobile_app/lumina_fintech/DESIGN.md
 * frontmatter. Do not edit these values by hand — change DESIGN.md and re-extract.
 */
export const lightPalette = {
  surface: '#faf8ff',
  surfaceDim: '#d2d9f4',
  surfaceBright: '#faf8ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f2f3ff',
  surfaceContainer: '#eaedff',
  surfaceContainerHigh: '#e2e7ff',
  surfaceContainerHighest: '#dae2fd',
  surfaceVariant: '#dae2fd',
  surfaceTint: '#494bd6',
  onSurface: '#131b2e',
  onSurfaceVariant: '#464554',
  inverseSurface: '#283044',
  inverseOnSurface: '#eef0ff',
  background: '#faf8ff',
  onBackground: '#131b2e',
  outline: '#767586',
  outlineVariant: '#c7c4d7',
  primary: '#4648d4',
  onPrimary: '#ffffff',
  primaryContainer: '#6063ee',
  onPrimaryContainer: '#fffbff',
  inversePrimary: '#c0c1ff',
  secondary: '#6b38d4',
  onSecondary: '#ffffff',
  secondaryContainer: '#8455ef',
  onSecondaryContainer: '#fffbff',
  tertiary: '#006c49',
  onTertiary: '#ffffff',
  tertiaryContainer: '#00885d',
  onTertiaryContainer: '#000703',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  primaryFixed: '#e1e0ff',
  primaryFixedDim: '#c0c1ff',
  onPrimaryFixed: '#07006c',
  onPrimaryFixedVariant: '#2f2ebe',
  secondaryFixed: '#e9ddff',
  secondaryFixedDim: '#d0bcff',
  onSecondaryFixed: '#23005c',
  onSecondaryFixedVariant: '#5516be',
  tertiaryFixed: '#6ffbbe',
  tertiaryFixedDim: '#4edea3',
  onTertiaryFixed: '#002113',
  onTertiaryFixedVariant: '#005236',
} as const;

export type PaletteColor = keyof typeof lightPalette;
