import { pbkdf2 } from '@noble/hashes/pbkdf2.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex, utf8ToBytes } from '@noble/hashes/utils.js';

/**
 * The master PIN: validation, key stretching and verification.
 *
 * Everything here is pure. The salt is generated by the caller (`lockStorage`,
 * which owns the one impure boundary) and passed in, so the derivation is
 * reproducible in a test without mocking a CSPRNG.
 *
 * A six-digit PIN is a space of one million. A single round of SHA-256 over it
 * is exhausted in milliseconds, so the PIN is stretched with PBKDF2-HMAC-SHA256
 * instead. That does not make the PIN strong; it makes an offline attack against
 * a stolen record cost days rather than nothing.
 *
 * The stretching is not the barrier that matters — the record lives in the
 * Keychain/Keystore, and anyone who can read it can also read the SQLCipher key
 * sitting beside it. It is the second lock, not the first.
 */

export const PIN_LENGTH = 6;

/** Bytes of salt. 16 is the PBKDF2 recommendation and the standard uniqueness margin. */
export const SALT_BYTES = 16;

/**
 * Below OWASP's 600,000 for PBKDF2-HMAC-SHA256, and deliberately so: this runs
 * in JavaScript on Hermes, where that figure costs several seconds on every
 * unlock. The record stores the count it was built with, so raising it later
 * re-derives on the next PIN change rather than locking out existing users.
 */
export const PBKDF2_ITERATIONS = 100_000;

const DERIVED_KEY_BYTES = 32;
const RECORD_VERSION = 1;

/** What is written to secure-store. Self-describing, so the parameters can change. */
export interface PinRecord {
  version: number;
  iterations: number;
  /** Hex. */
  salt: string;
  /** Hex. */
  hash: string;
}

export type PinProblem = 'length' | 'digits' | 'weak';

export type PinValidation = { ok: true } | { ok: false; problem: PinProblem };

/**
 * PINs that are guessed before any backoff can bite. Structural runs are caught
 * by the rules below; these are the memorable ones that no rule describes.
 */
const DENYLIST = new Set([
  '123456',
  '654321',
  '696969',
  '159753',
  '147258',
  '135790',
  '112233',
  '121212',
  '123123',
  '456789',
  '987654',
  '789456',
]);

function isRepeated(pin: string): boolean {
  return pin.split('').every((digit) => digit === pin[0]);
}

function isRun(pin: string, step: number): boolean {
  for (let index = 1; index < pin.length; index += 1) {
    if (Number(pin[index]) - Number(pin[index - 1]) !== step) {
      return false;
    }
  }

  return true;
}

/**
 * Rejects PINs that backoff cannot protect. A shoulder-surfer needs no attempts
 * at all, but an opportunist with the phone in hand gets five, and `000000` and
 * `123456` are inside the first five guesses on any list ever published.
 */
export function validatePin(pin: string): PinValidation {
  if (pin.length !== PIN_LENGTH) {
    return { ok: false, problem: 'length' };
  }

  if (!/^[0-9]+$/.test(pin)) {
    return { ok: false, problem: 'digits' };
  }

  if (isRepeated(pin) || isRun(pin, 1) || isRun(pin, -1) || DENYLIST.has(pin)) {
    return { ok: false, problem: 'weak' };
  }

  return { ok: true };
}

/** The stretched PIN, as hex. Pure: same PIN, salt and count give the same result. */
export function derivePinHash(pin: string, salt: string, iterations: number): string {
  const derived = pbkdf2(sha256, utf8ToBytes(pin), utf8ToBytes(salt), {
    c: iterations,
    dkLen: DERIVED_KEY_BYTES,
  });

  return bytesToHex(derived);
}

/**
 * `iterations` is a parameter rather than a constant read inside because the
 * record carries its own count: tests that are not measuring the stretching
 * build cheap records and still run the real derivation and comparison.
 */
export function buildPinRecord(
  pin: string,
  salt: string,
  iterations: number = PBKDF2_ITERATIONS,
): PinRecord {
  return {
    version: RECORD_VERSION,
    iterations,
    salt,
    hash: derivePinHash(pin, salt, iterations),
  };
}

/**
 * Compares in time independent of how many characters match. The threat is
 * remote at best — an attacker who can time this already has the record — but
 * an early-exit comparison in an authentication path is the kind of thing that
 * is cheaper to get right than to justify.
 */
function equalsConstantTime(left: string, right: string): boolean {
  if (left.length !== right.length) {
    return false;
  }

  let difference = 0;

  for (let index = 0; index < left.length; index += 1) {
    difference |= left.charCodeAt(index) ^ right.charCodeAt(index);
  }

  return difference === 0;
}

export function verifyPin(pin: string, record: PinRecord): boolean {
  // The record's own count, not the current constant: raising PBKDF2_ITERATIONS
  // must not invalidate a PIN that was enrolled under the old one.
  return equalsConstantTime(derivePinHash(pin, record.salt, record.iterations), record.hash);
}

export function serializePinRecord(record: PinRecord): string {
  return JSON.stringify(record);
}

/**
 * Returns null for anything that is not a well-formed record.
 *
 * A malformed record is treated as "no PIN is enrolled" rather than as an error,
 * which is the one place this differs from `getOrCreateDatabaseKey`. There the
 * stored value is irreplaceable and overwriting it destroys the vault; here it
 * is a verifier for a secret the user still knows, and leaving them permanently
 * unable to enrol is worse than making them set the PIN again.
 */
export function parsePinRecord(raw: string): PinRecord | null {
  let parsed: unknown;

  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }

  if (typeof parsed !== 'object' || parsed === null) {
    return null;
  }

  const { version, iterations, salt, hash } = parsed as Record<string, unknown>;

  if (
    version !== RECORD_VERSION ||
    typeof iterations !== 'number' ||
    !Number.isInteger(iterations) ||
    iterations < 1 ||
    typeof salt !== 'string' ||
    salt.length === 0 ||
    typeof hash !== 'string' ||
    hash.length !== DERIVED_KEY_BYTES * 2
  ) {
    return null;
  }

  return { version, iterations, salt, hash };
}
