/**
 * A real format-version-1, payload-version-1 backup, frozen at the moment F12
 * shipped.
 *
 * It is committed as bytes rather than regenerated by the test, because a
 * fixture the current code produces can only ever prove the current code agrees
 * with itself. This one was written by the build that shipped, so the day a
 * version 2 arrives there is already a genuinely older file in CI that must
 * still open — which is the whole claim the format's versioning makes.
 *
 * Passphrase: `the frozen fixture passphrase`. It protects nothing; the
 * contents are the same fake passport every other test uses. The iteration
 * count is 1,000 rather than the shipped 300,000 so opening it costs
 * milliseconds.
 *
 * **Do not regenerate this file.** If a change makes it unreadable, that change
 * is a breaking format change and needs a version bump and a migration.
 */

export const V1_CONTAINER_PASSWORD = 'the frozen fixture passphrase';

const V1_CONTAINER_BASE64 = [
  "RVZBVUxUAAEAAACreyJjaXBoZXIiOiJ4Y2hhY2hhMjBwb2x5MTMwNSIsImtkZiI6InBia2RmMi1z",
  "aGEyNTYiLCJpdGVyYXRpb25zIjoxMDAwLCJzYWx0IjoiMGIwYjBiMGIwYjBiMGIwYjBiMGIwYjBi",
  "MGIwYjBiMGIiLCJub25jZSI6IjBkMGQwZDBkMGQwZDBkMGQwZDBkMGQwZDBkMGQwZDBkMGQwZDBk",
  "MGQwZDBkMGQwZCJ9AAAAIrqvq9O5NBDnhB9mKkFlmzHYefRqgq4yam0gvPIxiJaXepoAAAgwvacD",
  "HD+byPwOEZ1vLYkQukMG34Mm1TSZ9aOSGjIH+0QviJqOTmER5LDk+ufAC2I/i6pPj9s3xAIPdnYt",
  "duVgzPe8yVLG38vOLKPfQJgE3a+g4y16w7wJ1O1TaLhYRxDAphdAgXkwFo0VWTaw9bd/xcWzuhOM",
  "1O6sjg7xhCMtq/vHwZHs6C/MYBEDFH9gHiHsVXfCkyGHyUB5sJ6VytgeEIH5UqBkZATZ4GlklqSG",
  "3pMBmgh+f8Oy3V46RXLXrqBH/XxypGqz6r6vqd6r2fgEfpNQ0mVaTc/yCPbPIPDoC4+WSVLZeaXA",
  "Uffo5u6SGJUbisoeL02RG8DmTIRXK/GdlL1VDi0ORFH0wgcgLjB5qS3x2E1SSqukYqtnp6aIFAzq",
  "+/pg+894hv7erqM62mTHERR5KZCaF77bvauYUaed1ibvW4QT6NCNB1yybdPxM0i1Mv0KXI1Ui0jZ",
  "sTNpn4R3rboAKltuBNormvZZxP388aYctbgwhdZEzhBbGhCJltHjt/To3qlnEaG7B2/RNw7VRnnX",
  "q41smW1TQHTfW/SUZKmbAj8tk2w+pu/v80TY+kyFn6BVogvkngX0Ogg9fiqafdWe8M08E56DLMUW",
  "8T6JZ57vdq6fT1tKcl3kjgxj4DcVuAIoqAIXXR7/LZsoZsCNjFhx7bzjDykwBsjA29WnO6q7KCYM",
  "OC91PyQGhWmiebUk1/tAMNHK2Uo3gyxDUqbpECB6zajbZ6gDJqateET30NOsGNwGFy5ImsWgvjB0",
  "/LqX/hdYb3JwLobihV/HRiLpErCH8KaBy+va7vCCyT4Xf4qyUtJHcr4iGKvkOFRaJk+IE1kVX1Zt",
  "ggjvIK/sLG3HSK5oTwofQyUvDiFfuVGW2ZnOKf6UQS9kMVeaZRTohcK3DpaG12COoCdDVUMmf3V+",
  "gVbMjMuRjY6jQsJ+p+doVzHEJKkgnn+i57MYA0dP/pyMQYpoeTecWzOu4T6VYuikulbdTav5QYZ0",
  "JFxpyB+lanJenRAh1WNgpwdsfGnLIJ9MY5j8+8FaXpiuIlTGWoiPeC0+uYJ7uZya3UqrIdJLHtZt",
  "DKNpzCqFG9ssdYPyiirleaq1BGvhX1hjkKRiMMoQxqoI9Oo7ZLTpDkh2WOH/IufEaNA/GmosXTp/",
  "XpeyciAs371tNSGWKH5rg+MyFRvwnx5/zNvD2+HagkZq+JMyKU8iyfIaxtVBIAtqo25IFnqCvPGQ",
  "ka0cw5dncxX2YFXqnBXln4z2rZ9odPIPJo06FCPPpm77DcHrlJCx7zmE47x3KUftQdbqO1TZ3sc2",
  "8G8jS+Ce2uyD1ouVZhCJ9PbKZHFpwMeLxIXZFxpfumhOw88C4GEfqNIHcQ2iFRHueGMmwi9tw7tg",
  "G4M03g9TzZRoTELOCilbc/3TXpszYp+tHzA9TBN04GJUriMLTEgO2Gn5iCdmOdEi2P+QSqW3C/6+",
  "Is7YFCOQ38V7M68CYgBXBqQ2wIFo8D+JXFF3FIJTj43dHtanNNen6Eqpbf8xX46jsiq94WrGHiAC",
  "+uKj7nt5+oVrkVPSL2P0KmUImaoQED0KMGer3TA70devX3rFuzcYXKiFIQEqm9wlkw1OrZ6e5M/f",
  "/GVcISirHhHUC7azFfR8ZRW9SBtdQbhDu/CvOfQpHvWFLf3jan9gPAx0ExxhdCZg/CIVc6WMx2QZ",
  "izM5Az0Xl/Njer8XFS82U36hLiDZesmcuVLvY4lc5qsz/n4vOsxs4fYAPJuG1tYm1yELuS+0R0po",
  "pCBZirx3/y18sJi5nrJ1Igljq7+WFFmT92A4QwokqWp0nuIVtH2T7rTSzHQNNO4Bqwkt2WmpyNW4",
  "xsxBluAR8TaEQUYnEO+1qpEsSPthZK0IH7YvKMWIMxfj8QLoxbumTC3xHu7wkpErTmQhfkkr+lHB",
  "ukGAhda8zl8SHFCYBVw0fj4WY3szGdslRRRgqEWjM/JwjVmAf8KrHI3RjkaQ/Xn4q7+fkCBdA3Qn",
  "i4Xvx5ec5Ve5QN83Nz2DYlG4VaWCt7/jFlzuw1kDA1o4Ad23sFFc/jhLgrZVq9h8le/uOLUBSNTI",
  "9R2mqnqROW5l+4jprJnW8v8Kxt4PvvkKq2wRfoCHyArPHXaCOpMC2NnSxyYekZPIEGA7V4tSMUNQ",
  "NX4QfmtpR0GJeQxgAKVK5HbVuz05yh27tXzSAMf6FsUrbOt6R+Bm3xnsn23zEaZhfVC5NVm3Emph",
  "U5q2OuoVWD+BCTGkYf8lqM7eIPXrqTqibIoe8pjQVsoLqeIC57ZSio/k7MzK4FC8gGJFaGMn9z5t",
  "PcDaFV043MU0Mu2cnZJCrgM/zqDpfxAvhL682yEM+sUZdwiXnt+OBCWYRUrD9DA7myK5RYtTxK1O",
  "0ELjnDqdHqU+xr99F2ab/KcgIxDL1QcZXJKgGZ0hQ9WadWtlb/7FgzXd1dP8x6s3Qz3hyf1xaq60",
  "hLBw5lGl/ybZpEug00gyb9oGU314840bxGFTVjcjH4mlmVj3+u3/m5rl/OMG03dvEk3euT2cNf6J",
  "tKzuHqOt38k2tqwG0esCCdEv3R3Ppa1dOn/MXNVSdjC3ScX0yY/0IuORqgEJfmW5UpTZQrNSrpQs",
  "5zYKBhFRcuYOfJRf3BRHHNhm11oTL1WJ8zkyF19d9uXqo122HHsuvJwDEh01ZS4fDJ7dzJ5q9cXy",
  "hITkoQwH3/WKf9v4I8naNlap8zR1sWIPvNiulfBmzFTYm1B8cbQx9eu6TK+9eie9qllCoEf9TPMO",
  "uTlRjhVTSYt96XMFuJC5nXS8/pcXZkwY6N8Wc7f6Fpi4I3bmxJ30xUwAAAAqCJS/QgxFgviucwdz",
  "WS4xr8tL3b/ABkayvjHEM8eFYCSyzMxE+jV/mdgW",].join('');

/** Decodes the fixture into the bytes an importer would read off disk. */
export function v1ContainerBytes(): Uint8Array {
  return Uint8Array.from(Buffer.from(V1_CONTAINER_BASE64, 'base64'));
}
